In [ ]:
import numpy as np

In [ ]:
rows = int(input("Enter the rank of matrix: "))
cols = rows

matrix = []
for i in range(rows):
  row = []
  for j in range(cols):
       element = float(input(f"Enter element at position ({i}, {j}): "))
       row.append(element)
  matrix.append(row)

matrix = np.array(matrix)

for i in range(rows):
  if(matrix[i,i]==0):
    print("Choose another matrix, as diagonal zero")


print(matrix)

Enter the rank of matrix: 3
Enter element at position (0, 0): 10
Enter element at position (0, 1): -7
Enter element at position (0, 2): 0
Enter element at position (1, 0): -3
Enter element at position (1, 1): 2.099
Enter element at position (1, 2): 6
Enter element at position (2, 0): 5
Enter element at position (2, 1): -1
Enter element at position (2, 2): 5
[[10.    -7.     0.   ]
 [-3.     2.099  6.   ]
 [ 5.    -1.     5.   ]]


In [ ]:
D = []
for i in range(rows):
    element = float(input(f"Enter element at position ({i}): "))
    D.append(element)
D = np.array(D)

Enter element at position (0): 7
Enter element at position (1): 3.901
Enter element at position (2): 6


In [ ]:
FS(matrix,D,rows)

[2.5 1.4]


In [ ]:
BS(matrix,D,rows)

[-3.10862447e-13 -1.00000000e+00  1.00000000e+00]


# Gaussian Elimination

In [ ]:
n=rows
for k in range(n-1):
  for i in range(k+1,n):
    t= matrix[i,k]/matrix[k,k]
    matrix[i,k]=0
    D[i]=D[i]-t*D[k]
    for j in range(k+1,n):
      matrix[i,j]=matrix[i,j]-t*matrix[k,j]

print(matrix)
print(D)


[[9.         5.        ]
 [0.         7.44444444]]
[ 7.         -2.77777778]


# Forward Substitution(LTM)

In [ ]:
def FS(matrix,D,rows):
  X=np.zeros(rows)
  for i in range(rows):
    temp=D[i]
    for j in range(i):
      temp = temp - matrix[i,j]*X[j]
    X[i] = temp/matrix[i,i]

  return print(X)

# Back Substitution(UTM)

In [ ]:
def BS(matrix,D,rows):
  Y=np.zeros(rows)
  for i in range(rows-1, -1, -1):
        tmp = D[i]
        for j in range(i+1, rows):
          tmp = tmp - matrix[i,j] * Y[j]
        Y[i] = tmp / matrix[i,i]

  return print(Y)

# GAUSSIAN WITH PIVOT

In [ ]:
def swap_rows(matrix, row1, row2):
   matrix[[row1, row2]] = matrix[[row2, row1]]

In [ ]:
p=[0]*n
n=rows
for i in range(0,n):
  p[i]=i

for k in range(0,n-1):
  m=k
  for i in range(k+1,n):
    if(abs(matrix[p[m],k]) < abs(matrix[p[i],k])):
      m=i

  l=p[k]
  p[k]=p[m]
  p[m]=l


  for i in range(k+1,n):
    matrix[p[i],k]=matrix[p[i],k]/matrix[p[k],k]

    for j in range(k,n):
      matrix[p[i],j]=matrix[p[i],j]-matrix[p[i],k]*matrix[p[k],j]


print(matrix)
print(D)

[[10.    -7.     0.   ]
 [-3.     2.099  6.   ]
 [ 5.    -1.     5.   ]]
[[ 1.0000e+01 -7.0000e+00  0.0000e+00]
 [ 0.0000e+00 -1.0000e-03  6.0000e+00]
 [ 0.0000e+00  0.0000e+00  1.5005e+04]]
[[ 1.0000e+01 -7.0000e+00  0.0000e+00]
 [ 0.0000e+00 -1.0000e-03  6.0000e+00]
 [ 0.0000e+00  0.0000e+00  1.5005e+04]]
[7.0000e+00 6.0010e+00 1.5005e+04]
